//
//  PBImageView.m
//  PokeBattle
//
//  Created by sakamoto on 2014/08/02.
//  Copyright (c) 2014年 YoshikiAkino. All rights reserved.
//

#import "PBImageView.h"

@implementation PBImageView
@synthesize textView;


- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
    }
    return self;
}

- (id)initWithImageNameAndText:(NSString *)image_name imagePath:(NSString *)imagePath textString:(NSString *)textString characterIsOnLeft:(BOOL)characterIsOnLeft{
    self = [super initWithImage:[UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"whiteBack" ofType:@"png"]]];
    if(self){
        // initialization code
        self.userInteractionEnabled = YES;
        super.frame = CGRectMake(0, [UIScreen mainScreen].bounds.size.height - 100 , [UIScreen mainScreen].bounds.size.width, 100);
        
        textView = [[UITextView alloc] init];
        [super addSubview:textView];
        [textView setFont:[UIFont systemFontOfSize:16.0f]];
        textView.userInteractionEnabled = YES;
        textView.editable = NO;
        [PenetrateFilter penetrate:textView];
        textView.text = textString;
        
        UIImageView *characterAnimation = [[UIImageView alloc] initWithImage:[UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:image_name ofType:imagePath]]];
        characterAnimation.contentMode = UIViewContentModeScaleAspectFit;
        [super addSubview:characterAnimation];
        if (characterIsOnLeft) {
            textView.frame = CGRectMake(105 , 5, [UIScreen mainScreen].bounds.size.width - 110, 90);
            characterAnimation.frame = CGRectMake(0, 0, 100, 100);
        }else{
            textView.frame = CGRectMake(5 , 5, [UIScreen mainScreen].bounds.size.width - 110, 90);
            characterAnimation.frame = CGRectMake([UIScreen mainScreen].bounds.size.width - 100, 0, 100, 100);
        }
    }
    
    //最前面に来ているビューコントローラを取得
    rootViewController = [UIApplication sharedApplication].keyWindow.rootViewController;
    while (rootViewController.presentedViewController) {
        rootViewController = rootViewController.presentedViewController;
    }
    return self;
}

- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event{
    NSLog(@"タッチ");
    //アニメーションの対象となるコンテキスト
    CGContextRef context = UIGraphicsGetCurrentContext();
    [UIView beginAnimations:nil context:context];
    //アニメーションを実行する時間
    [UIView setAnimationDuration:0.2];
    //アニメーションイベントを受け取るview
    [UIView setAnimationDelegate:self];
    //アニメーション終了後に実行される
    [UIView setAnimationDidStopSelector:@selector(removeFromSuperview)];
    
    self.alpha = 0.0;
    
    // アニメーション開始
    [UIView commitAnimations];
}

//- (void)startAnimation001{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro001" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation002)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation002)]];}
//- (void)startAnimation002{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro002" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation003)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation003)]];}
//- (void)startAnimation003{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro003" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation004)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation004)]];}
//- (void)startAnimation004{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro004" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation005)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation005)]];}
//- (void)startAnimation005{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro005" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation006)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation006)]];}
//- (void)startAnimation006{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro006" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation007)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation007)]];}
//- (void)startAnimation007{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro007" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation008)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation008)]];}
//- (void)startAnimation008{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro008" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation009)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation009)]];}
//- (void)startAnimation009{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro009" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation010)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation010)]];}
//- (void)startAnimation010{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro010" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation011)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation011)]];}
//- (void)startAnimation011{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro011" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation012)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation012)]];}
//- (void)startAnimation012{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro012" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation013)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation013)]];}
//- (void)startAnimation013{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro013" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation014)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation014)]];}
//- (void)startAnimation014{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro014" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation015)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation015)]];}
//- (void)startAnimation015{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro015" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation016)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation016)]];}
//- (void)startAnimation016{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro016" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation017)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation017)]];}
//- (void)startAnimation017{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro017" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation018)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation018)]];}
//- (void)startAnimation018{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro018" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation019)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation019)]];}
//- (void)startAnimation019{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro019" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation020)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation020)]];}
//- (void)startAnimation020{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro020" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation021)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation021)]];}
//- (void)startAnimation021{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro021" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation022)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation022)]];}
//- (void)startAnimation022{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro022" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation023)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation023)]];}
//- (void)startAnimation023{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro023" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation024)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation024)]];}
//- (void)startAnimation024{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro024" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation025)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation025)]];}
//- (void)startAnimation025{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro025" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation026)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation026)]];}
//- (void)startAnimation026{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro026" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation027)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation027)]];}
//- (void)startAnimation027{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro027" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation028)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation028)]];}
//- (void)startAnimation028{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro028" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation029)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation029)]];}
//- (void)startAnimation029{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro029" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation030)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation030)]];}
//- (void)startAnimation030{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro030" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation031)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation031)]];}
//- (void)startAnimation031{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro031" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation032)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation032)]];}
//- (void)startAnimation032{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro032" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation033)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation033)]];}
//- (void)startAnimation033{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro033" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation034)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation034)]];}
//- (void)startAnimation034{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro034" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation035)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation035)]];}
//- (void)startAnimation035{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro035" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation036)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation036)]];}
//- (void)startAnimation036{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro036" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation037)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation037)]];}
//- (void)startAnimation037{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro037" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation038)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation038)]];}
//- (void)startAnimation038{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro038" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation039)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation039)]];}
//- (void)startAnimation039{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro039" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation040)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation040)]];}
//- (void)startAnimation040{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro040" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation041)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation041)]];}
//- (void)startAnimation041{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro041" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation042)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation042)]];}
//- (void)startAnimation042{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro042" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation043)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation043)]];}
//- (void)startAnimation043{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro043" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation044)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation044)]];}
//- (void)startAnimation044{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro044" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation045)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation045)]];}
//- (void)startAnimation045{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro045" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation046)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation046)]];}
//- (void)startAnimation046{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro046" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation047)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation047)]];}
//- (void)startAnimation047{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro047" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation048)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation048)]];}
//- (void)startAnimation048{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro048" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation049)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation049)]];}
//- (void)startAnimation049{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro049" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation050)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation050)]];}
//- (void)startAnimation050{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro050" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation051)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation051)]];}
//- (void)startAnimation051{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro051" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation052)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation052)]];}
//- (void)startAnimation052{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro052" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation053)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation053)]];}
//- (void)startAnimation053{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro053" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation054)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation054)]];}
//- (void)startAnimation054{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro054" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation055)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation055)]];}
//- (void)startAnimation055{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro055" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation056)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation056)]];}
//- (void)startAnimation056{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro056" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation057)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation057)]];}
//- (void)startAnimation057{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro057" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation058)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation058)]];}
//- (void)startAnimation058{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro058" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation059)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation059)]];}
//- (void)startAnimation059{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro059" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation060)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation060)]];}
//- (void)startAnimation060{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro060" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation061)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation061)]];}
//- (void)startAnimation061{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro061" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation062)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation062)]];}
//- (void)startAnimation062{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro062" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation063)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation063)]];}
//- (void)startAnimation063{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro063" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation064)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation064)]];}
//- (void)startAnimation064{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro064" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation065)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation065)]];}
//- (void)startAnimation065{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro065" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation066)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation066)]];}
//- (void)startAnimation066{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro066" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation067)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation067)]];}
//- (void)startAnimation067{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro067" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation068)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation068)]];}
//- (void)startAnimation068{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro068" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation069)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation069)]];}
//- (void)startAnimation069{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro069" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation070)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation070)]];}
//- (void)startAnimation070{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro070" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation071)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation071)]];}
//- (void)startAnimation071{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro071" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation072)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation072)]];}
//- (void)startAnimation072{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro072" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation073)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation073)]];}
//- (void)startAnimation073{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro073" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation074)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation074)]];}
//- (void)startAnimation074{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro074" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation075)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation075)]];}
//- (void)startAnimation075{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro075" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation076)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation076)]];}
//- (void)startAnimation076{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro076" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation077)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation077)]];}
//- (void)startAnimation077{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro077" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation078)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation078)]];}
//- (void)startAnimation078{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro078" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation079)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation079)]];}
//- (void)startAnimation079{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro079" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation080)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation080)]];}
//- (void)startAnimation080{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro080" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation081)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation081)]];}
//- (void)startAnimation081{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro081" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation082)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation082)]];}
//- (void)startAnimation082{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro082" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation083)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation083)]];}
//- (void)startAnimation083{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro083" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation084)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation084)]];}
//- (void)startAnimation084{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro084" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation085)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation085)]];}
//- (void)startAnimation085{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro085" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation086)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation086)]];}
//- (void)startAnimation086{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro086" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation087)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation087)]];}
//- (void)startAnimation087{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro087" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation088)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation088)]];}
//- (void)startAnimation088{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro088" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation089)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation089)]];}
//- (void)startAnimation089{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro089" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation090)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation090)]];}
//- (void)startAnimation090{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro090" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation091)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation091)]];}
//- (void)startAnimation091{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro091" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation092)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation092)]];}
//- (void)startAnimation092{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro092" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation093)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation093)]];}
//- (void)startAnimation093{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro093" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation094)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation094)]];}
//- (void)startAnimation094{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro094" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation095)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation095)]];}
//- (void)startAnimation095{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro095" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation096)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation096)]];}
//- (void)startAnimation096{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro096" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation097)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation097)]];}
//- (void)startAnimation097{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro097" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation098)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation098)]];}
//- (void)startAnimation098{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro098" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation099)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation099)]];}
//- (void)startAnimation099{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro099" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation100)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation100)]];}
//- (void)startAnimation100{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro100" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation101)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation101)]];}
//- (void)startAnimation101{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro101" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation102)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation102)]];}
//- (void)startAnimation102{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro102" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation103)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation103)]];}
//- (void)startAnimation103{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro103" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation104)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation104)]];}
//- (void)startAnimation104{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro104" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation105)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation105)]];}
//- (void)startAnimation105{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro105" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation106)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation106)]];}
//- (void)startAnimation106{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro106" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation107)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation107)]];}
//- (void)startAnimation107{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro107" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation108)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation108)]];}
//- (void)startAnimation108{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro108" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation109)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation109)]];}
//- (void)startAnimation109{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro109" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation110)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation110)]];}
//- (void)startAnimation110{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro110" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation111)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation111)]];}
//- (void)startAnimation111{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro111" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation112)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation112)]];}
//- (void)startAnimation112{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro112" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation113)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation113)]];}
//- (void)startAnimation113{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro113" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation114)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation114)]];}
//- (void)startAnimation114{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro114" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation115)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation115)]];}
//- (void)startAnimation115{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro115" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation116)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation116)]];}
//- (void)startAnimation116{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro116" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation117)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation117)]];}
//- (void)startAnimation117{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro117" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation118)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation118)]];}
//- (void)startAnimation118{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro118" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation119)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation119)]];}
//- (void)startAnimation119{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro119" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation120)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation120)]];}
//- (void)startAnimation120{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro120" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation121)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation121)]];}
//- (void)startAnimation121{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro121" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation122)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation122)]];}
//- (void)startAnimation122{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro122" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation123)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation123)]];}
//- (void)startAnimation123{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro123" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation124)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation124)]];}
//- (void)startAnimation124{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro124" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation125)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation125)]];}
//- (void)startAnimation125{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro125" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation126)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation126)]];}
//- (void)startAnimation126{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro126" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation127)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation127)]];}
//- (void)startAnimation127{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro127" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation128)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation128)]];}
//- (void)startAnimation128{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro128" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation129)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation129)]];}
//- (void)startAnimation129{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro129" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation130)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation130)]];}
//- (void)startAnimation130{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro130" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation131)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation131)]];}
//- (void)startAnimation131{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro131" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation132)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation132)]];}
//- (void)startAnimation132{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro132" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation133)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation133)]];}
//- (void)startAnimation133{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro133" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation134)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation134)]];}
//- (void)startAnimation134{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro134" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation135)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation135)]];}
//- (void)startAnimation135{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro135" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation136)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation136)]];}
//- (void)startAnimation136{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro136" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation137)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation137)]];}
//- (void)startAnimation137{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro137" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation138)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation138)]];}
//- (void)startAnimation138{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro138" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation139)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation139)]];}
//- (void)startAnimation139{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro139" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation140)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation140)]];}
//- (void)startAnimation140{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro140" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation141)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation141)]];}
//- (void)startAnimation141{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro141" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation142)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation142)]];}
//- (void)startAnimation142{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro142" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation143)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation143)]];}
//- (void)startAnimation143{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro143" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation144)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation144)]];}
//- (void)startAnimation144{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro144" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation145)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation145)]];}
//- (void)startAnimation145{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro145" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation146)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation146)]];}
//- (void)startAnimation146{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro146" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation147)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation147)]];}
//- (void)startAnimation147{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro147" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation148)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation148)]];}
//- (void)startAnimation148{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro148" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation149)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation149)]];}
//- (void)startAnimation149{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro149" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation150)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation150)]];}
//- (void)startAnimation150{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro150" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation151)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation151)]];}
//- (void)startAnimation151{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro151" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation152)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation152)]];}
//- (void)startAnimation152{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro152" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation153)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation153)]];}
//- (void)startAnimation153{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro153" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation154)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation154)]];}
//- (void)startAnimation154{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro154" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation155)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation155)]];}
//- (void)startAnimation155{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro155" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation156)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation156)]];}
//- (void)startAnimation156{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro156" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation157)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation157)]];}
//- (void)startAnimation157{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro157" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation158)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation158)]];}
//- (void)startAnimation158{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro158" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation159)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation159)]];}
//- (void)startAnimation159{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro159" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation160)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation160)]];}
//- (void)startAnimation160{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro160" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation161)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation161)]];}
//- (void)startAnimation161{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro161" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation162)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation162)]];}
//- (void)startAnimation162{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro162" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation163)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation163)]];}
//- (void)startAnimation163{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro163" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation164)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation164)]];}
//- (void)startAnimation164{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro164" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation165)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation165)]];}
//- (void)startAnimation165{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro165" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation166)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation166)]];}
//- (void)startAnimation166{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro166" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation167)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation167)]];}
//- (void)startAnimation167{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro167" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation168)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation168)]];}
//- (void)startAnimation168{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro168" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation169)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation169)]];}
//- (void)startAnimation169{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro169" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation170)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation170)]];}
//- (void)startAnimation170{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro170" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation171)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation171)]];}
//- (void)startAnimation171{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro171" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation172)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation172)]];}
//- (void)startAnimation172{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro172" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation173)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation173)]];}
//- (void)startAnimation173{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro173" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation174)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation174)]];}
//- (void)startAnimation174{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro174" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation175)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation175)]];}
//- (void)startAnimation175{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro175" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation176)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation176)]];}
//- (void)startAnimation176{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro176" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation177)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation177)]];}
//- (void)startAnimation177{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro177" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation178)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation178)]];}
//- (void)startAnimation178{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro178" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation179)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation179)]];}
//- (void)startAnimation179{    PBImageView *pbImage = [[PBImageView alloc] initWithImageNameAndText:@"pro179" imagePath:@"png" textString:@"" characterIsOnLeft:YES];    [self.view addSubview:pbImage];    [pbImage addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation180)]];    [pbImage.textView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(startAnimation180)]];}

@end
